language: node_js
node_js:
  - 8.9.1

branches:
  only:
  - master

addons:
  chrome: stable

before_install:
  - yarn global add @angular/cli

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - yarn install

script:
  - yarn run test:single-run
